[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --omit=dev --force"]

[start]
cmd = "mkdir -p meshcentral-data && cp -f meshcentral-default-config.json meshcentral-data/config.json && node meshcentral.js"
